# Generated by Django 3.2.6 on 2021-08-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(max_length=30)),
                ('default', models.CharField(max_length=30)),
                ('balance', models.IntegerField(max_length=30)),
                ('duration', models.IntegerField(max_length=30)),
                ('campaign', models.IntegerField(max_length=30)),
                ('pdays', models.IntegerField(max_length=30)),
                ('previous', models.IntegerField(max_length=30)),
            ],
        ),
    ]
