# Generated by Django 3.2.6 on 2021-08-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='y',
            field=models.IntegerField(default=0, max_length=30),
        ),
    ]
